name: Bug Report
description: Report a bug in the CI/CD pipeline or application
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area is affected?
      options:
        - CI/CD Pipeline
        - API Endpoints
        - Database
        - Testing (Jest)
        - Testing (Keploy)
        - Build/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: If applicable, add screenshots or logs to help explain your problem.

  - type: input
    id: branch
    attributes:
      label: Branch/Commit
      description: Which branch or commit hash is affected?
      placeholder: main, feature/xyz, or commit hash

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this occur?
      options:
        - GitHub Actions CI
        - Local Development
        - Production
        - Docker Container
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. 